import time
print("Starting Attacking......")
time.sleep(3)
print("Hacking Nasa 0% ")
time.sleep(5)
print("Hacking Nasa 20% ")
time.sleep(7)
print("Hacking Nasa 40% ")
time.sleep(10)
print("Hacking Nasa 60% ")
time.sleep(10)
print("Hacking Nasa 60% ")
time.sleep(3)
print("Hacking Nasa 80% ")
time.sleep(6)
print("Hacking Nasa 60% ")
time.sleep(8)
print("Done Hacking")